//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UncleChao.CompanyManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Experience = new HashSet<Experience>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Experience> Experience { get; set; }
    }
}
